steps:
  - label: ":bazel: Setup & Cache"
    key: "setup"
    command: |
      echo "--- :bazel: Bazel version"
      bazel version
      echo "--- :package: Fetching dependencies"
      bazel fetch //...
    agents:
      queue: "selfhosted"
      os: "linux"

  - wait

  # Run tests and build in parallel
  - label: ":test_tube: Run All Tests"
    key: "tests"
    command: |
      echo "--- :junit: Running unit tests"
      bazel test //src/test/... --test_output=errors --test_summary=detailed

      echo "--- :bar_chart: Test results"
      bazel test //src/test/... --test_output=errors || true
    artifact_paths:
      - "bazel-testlogs/**/test.log"
      - "bazel-testlogs/**/test.xml"
    plugins:
      # JUnit annotation plugin for inline test failure annotations
      - junit-annotate#v2.7.0:
          artifacts: "bazel-testlogs/**/test.xml"
          context: "junit-annotations"
          fail-build-on-error: false
          report-slowest: 10
          job-uuid-file-pattern: ".*/([^/]*)/test.xml"
      # Test Analytics - Track test trends over time
      - test-collector#v1.11.0:
          files: "bazel-testlogs/**/test.xml"
          format: "junit"
          follow_symlinks: false
    agents:
      queue: "selfhosted"
      os: "linux"

  - label: ":package: Build All Solutions"
    key: "build"
    command: |
      echo "--- :bazel: Building all day solutions"
      bazel build //src/main/com/stiksy/aoc2025/...

      echo "--- :white_check_mark: Build successful"
      bazel build //src/main/com/stiksy/aoc2025/... --show_result=10
    agents:
      queue: "selfhosted"
      os: "linux"

  - wait

  # Dynamically generate steps for all completed days
  - group: ":christmas_tree: Daily Challenge Results"
    key: "daily-results"
    steps:
      - label: ":gear: Generate Day Steps"
        command: |
          echo "--- :mag: Discovering completed days"
          bash scripts/generate_day_steps.sh | buildkite-agent pipeline upload
        agents:
          queue: "selfhosted"
          os: "linux"

  - wait

  - label: ":chart_with_upwards_trend: Final Summary"
    command: |
      echo "--- :trophy: Advent of Code 2025 Summary"
      echo ""
      echo "All tests passed! ✅"
      echo "All solutions built successfully! ✅"
      echo ""
      echo "View annotations above for individual day results."
      echo ""
      echo "Repository: https://github.com/stiksy/advent-of-code-2025"
    agents:
      queue: "selfhosted"
      os: "linux"
